Repository open-telemetry/weaver, pull requests merged in 2024-06, with the labels that each got.

#187 Generate JSON Schema for both Resolved Telemetry Schema and Resolved Registry
  Cargo.lock
  Cargo.toml
  crates/weaver_codegen_test/build.rs
  crates/weaver_common/src/in_memory.rs
  crates/weaver_common/src/lib.rs
  crates/weaver_common/src/quiet.rs
  crates/weaver_forge/Cargo.toml
  crates/weaver_forge/allowed-external-types.toml
  crates/weaver_forge/src/lib.rs
  crates/weaver_forge/src/registry.rs
  crates/weaver_resolved_schema/Cargo.toml
  crates/weaver_resolved_schema/allowed-external-types.toml
  crates/weaver_resolved_schema/src/attribute.rs
  crates/weaver_resolved_schema/src/catalog.rs
  crates/weaver_resolved_schema/src/instrumentation_library.rs
  crates/weaver_resolved_schema/src/lib.rs
  crates/weaver_resolved_schema/src/lineage.rs
  crates/weaver_resolved_schema/src/metric.rs
  crates/weaver_resolved_schema/src/registry.rs
  crates/weaver_resolved_schema/src/resource.rs
  crates/weaver_resolved_schema/src/signal.rs
  crates/weaver_resolved_schema/src/tags.rs
  crates/weaver_resolved_schema/src/value.rs
  crates/weaver_semconv/Cargo.toml
  crates/weaver_semconv/allowed-external-types.toml
  crates/weaver_semconv/src/attribute.rs
  crates/weaver_semconv/src/group.rs
  crates/weaver_semconv/src/stability.rs
  crates/weaver_semconv_gen/src/lib.rs
  crates/weaver_version/Cargo.toml
  crates/weaver_version/allowed-external-types.toml
  crates/weaver_version/src/lib.rs
  crates/weaver_version/src/logs_change.rs
  crates/weaver_version/src/logs_version.rs
  crates/weaver_version/src/metrics_change.rs
  crates/weaver_version/src/metrics_version.rs
  crates/weaver_version/src/resource_change.rs
  crates/weaver_version/src/resource_version.rs
  crates/weaver_version/src/spans_change.rs
  crates/weaver_version/src/spans_version.rs
  docs/images/dependencies.svg
  src/cli.rs
  src/diagnostic/init.rs
  src/format.rs
  src/main.rs
  src/registry/check.rs
  src/registry/generate.rs
  src/registry/json_schema.rs
  src/registry/mod.rs
  src/registry/resolve.rs
  src/registry/stats.rs
  src/registry/update_markdown.rs
  src/util.rs
Labels: enhancement

#195 [WIP] Support command line parameters to add an additional layer of configurability in the documentation/code generator.
  Cargo.lock
  crates/weaver_codegen_test/build.rs
  crates/weaver_codegen_test/templates/registry/rust/attributes/mod.rs.j2
  crates/weaver_codegen_test/templates/registry/rust/metrics/mod.rs.j2
  crates/weaver_codegen_test/templates/registry/rust/weaver.yaml
  crates/weaver_codegen_test/tests/codegen.rs
  crates/weaver_forge/README.md
  crates/weaver_forge/allowed-external-types.toml
  crates/weaver_forge/src/config.rs
  crates/weaver_forge/src/filter.rs
  crates/weaver_forge/src/lib.rs
  crates/weaver_semconv_gen/src/lib.rs
  docs/weaver-config.md
  src/main.rs
  src/registry/generate.rs
  src/registry/mod.rs
  src/registry/update_markdown.rs
Labels: enhancement

#196 chore(release): Prepare for release 0.4.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/weaver_cache/Cargo.toml
  crates/weaver_checker/Cargo.toml
  crates/weaver_codegen_test/Cargo.toml
  crates/weaver_common/Cargo.toml
  crates/weaver_diff/Cargo.toml
  crates/weaver_forge/Cargo.toml
  crates/weaver_forge/src/lib.rs
  crates/weaver_resolved_schema/Cargo.toml
  crates/weaver_resolver/Cargo.toml
  crates/weaver_semconv/Cargo.toml
  crates/weaver_semconv_gen/Cargo.toml
  crates/weaver_version/Cargo.toml
  src/cli.rs
  tests/registry_check.rs
Labels: ci/cd

#200 feat(forge): Add `semconv_const` filter to support semantic convention namespacing rules.
  Cargo.lock
  crates/weaver_forge/README.md
  crates/weaver_forge/src/error.rs
  crates/weaver_forge/src/extensions/case.rs
  crates/weaver_forge/src/extensions/otel.rs
Labels: enhancement

#209 New entry in developer guide to describe the process of adding new fields in the semantic convention registry
  docs/developer-guide.md
Labels: documentation

#214 Add support for post-resolution policies
  Cargo.lock
  crates/weaver_checker/Cargo.toml
  crates/weaver_checker/src/lib.rs
  crates/weaver_codegen_test/semconv_registry/http-post-resolution-policies.rego
  crates/weaver_codegen_test/semconv_registry/metrics-post-resolution-policies.rego
  crates/weaver_codegen_test/semconv_registry/otel-pre-resolution-policies.rego
  crates/weaver_common/src/diagnostic.rs
  crates/weaver_semconv/src/path.rs
  crates/weaver_semconv/src/semconv.rs
  src/registry/check.rs
  src/registry/generate.rs
  src/registry/resolve.rs
  src/util.rs
  tests/registry_check.rs
Labels: enhancement

#212 Embed for attributes
  crates/weaver_forge/src/extensions/otel.rs
  crates/weaver_resolved_schema/src/attribute.rs
  crates/weaver_resolved_schema/src/lineage.rs
  crates/weaver_resolver/data/registry-test-10-prefix-refs/README.md
  crates/weaver_resolver/data/registry-test-10-prefix-refs/expected-attribute-catalog.json
  crates/weaver_resolver/data/registry-test-10-prefix-refs/expected-registry.json
  crates/weaver_resolver/data/registry-test-10-prefix-refs/registry/client.yaml
  crates/weaver_resolver/data/registry-test-10-prefix-refs/registry/geo.yaml
  crates/weaver_resolver/data/registry-test-10-prefix-refs/registry/usage.yaml
  crates/weaver_resolver/data/registry-test-11-prefix-refs-extends/README.md
  crates/weaver_resolver/data/registry-test-11-prefix-refs-extends/expected-attribute-catalog.json
  crates/weaver_resolver/data/registry-test-11-prefix-refs-extends/expected-registry.json
  crates/weaver_resolver/data/registry-test-11-prefix-refs-extends/registry/client.yaml
  crates/weaver_resolver/data/registry-test-11-prefix-refs-extends/registry/geo.yaml
  crates/weaver_resolver/data/registry-test-11-prefix-refs-extends/registry/usage.yaml
  crates/weaver_resolver/data/registry-test-11-prefix-refs-extends/registry/usage2.yaml
  crates/weaver_resolver/src/attribute.rs
  crates/weaver_resolver/src/registry.rs
  crates/weaver_semconv/src/attribute.rs
Labels: enhancement
