Repository open-telemetry/weaver, pull requests merged in 2025-04, with the labels that each got.

#697 Fix division by zero and incorrect attribute counting in weaver registry stats command
  Cargo.lock
  crates/weaver_resolved_schema/Cargo.toml
  crates/weaver_resolved_schema/src/attribute.rs
  crates/weaver_resolved_schema/src/registry.rs
  crates/weaver_resolver/src/attribute.rs
  crates/weaver_resolver/src/registry.rs
  src/registry/stats.rs
  tests/registry_stats.rs
Labels: bug

#682 Add tab completions from clap_complete.
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  docs/usage.md
  src/cli.rs
  src/main.rs
  tests/completion_check.rs
Labels: enhancement, ux

#700 Support remote templates and policies
  CHANGELOG.md
  README.md
  crates/weaver_common/src/lib.rs
  src/registry/generate.rs
  src/registry/mod.rs
  src/registry/update_markdown.rs
  src/util.rs
Labels: enhancement, ux

#630 Weaver Live Check System
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/weaver_checker/src/lib.rs
  crates/weaver_checker/src/violation.rs
  crates/weaver_emit/data/otel.yaml
  crates/weaver_forge/src/lib.rs
  crates/weaver_live_check/Cargo.toml
  crates/weaver_live_check/README.md
  crates/weaver_live_check/allowed-external-types.toml
  crates/weaver_live_check/data/attributes.json
  crates/weaver_live_check/data/attributes.txt
  crates/weaver_live_check/data/jq/test.jq
  crates/weaver_live_check/data/policies/live_check_advice/test.rego
  crates/weaver_live_check/data/span.json
  crates/weaver_live_check/src/advice.rs
  crates/weaver_live_check/src/json_file_ingester.rs
  crates/weaver_live_check/src/json_stdin_ingester.rs
  crates/weaver_live_check/src/lib.rs
  crates/weaver_live_check/src/live_checker.rs
  crates/weaver_live_check/src/sample_attribute.rs
  crates/weaver_live_check/src/sample_resource.rs
  crates/weaver_live_check/src/sample_span.rs
  crates/weaver_live_check/src/text_file_ingester.rs
  crates/weaver_live_check/src/text_stdin_ingester.rs
  defaults/jq/advice.jq
  defaults/live_check_templates/ansi/live_check.txt.j2
  defaults/live_check_templates/ansi/live_check_macros.j2
  defaults/live_check_templates/ansi/weaver.yaml
  defaults/live_check_templates/json/live_check.json.j2
  defaults/live_check_templates/json/weaver.yaml
  defaults/policies/live_check_advice/otel.rego
  src/registry/live_check.rs
  src/registry/mod.rs
  src/registry/otlp/mod.rs
  src/registry/otlp/otlp_ingester.rs
  tests/registry_emit.rs
Labels: enhancement
